language: python
matrix:
  include:
    - python: 3.7
        dist: xenial
        sudo: true
install:
    - pip install -e .
script:
    - pip install 'pytest>=3.6' pytest-coveralls
    - cd tests
    - py.test -v --cov=minus80
after_success:
    - coveralls
    - cd ../
deploy:
  provider: pypi
  user: schae234
  password:
    secure: wqudCGOByU7YA+R97D+lepV4BrFmizRPcQqrbHCNlRMlIJkw4sZQwRMEKcdqN4VrXjlyw1AyErwwJ2s76/PdFTlBofiUyLvBTw3Pki7PzWwYNzgTMHmGS8vWLp6nq84WMm1x3J3dxX4H/M7Sh9EkqsomAkwmXj0dMtfgfwjN/LGGy9Fv7P5174Ej0MnbQWTq+JRNUKUKxWH5XuUfTeexR40KxGMHR9gyarteewNUx3QmYnrN5RPxOsd8tdDo0R7Fgj/NWB1f/DLaj5JweykRcVtzwuZrQR3mTnbopVhkz3wbaKY4f/zqdlE6irFiNrPu3kEnz4Yt8NYpgyzhRhzskxGAoXil2m9DQVSQC9R5ovTYUxe5iyO4jbsd/Hx+DogSOdbDLGnAlTb3cbl5OQUKIjLpbkbJ2YiGcTlNcfaQ4q8f1Gg+zmyFjsNpwfdMikuIYlchjtpe/+AxGORZzHHzR8bP2ltlJ74C/avlNtPuL9BqkKEEBryaUcQyELKso9WLzV8C3iAHxEgDeIGI9eEgyX5FdR0IYYgOCYhVU+2sWYErSoyBPxXyLyR5FHXBGDJDjZEcbY33bJg06E/rFl2NW6s9LaSc0YCj3W+PwnNIE6nzLhbKXM419vCGPKLY1GQ5CBbM+SpMJT4hVBSsolH0dqBg3RsaMQa3gFSSyweCIKs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: LinkageIO/Minus80
